Propar och motioner ht18
dtekcth/styrdokument pull request #11
Opened 2019-02-12 20:00 UTC by viktorhallen

Hej, kolla igenom plz så blir jag glad :)

2019-02-19 22:27 UTC, Kirens commented on reglemente/hobbykommitteer.tex
> +%  \item DDD % save for future, finns la ingen nackdel?
sneaky...

2019-03-04 13:59 UTC, Hugsim commented on stadgar/stadgar.tex
> +Datateknologsektionen vid Chalmers, härmed benämnd teknologsektionen, är en ideell kommitté bestående av studerande vid utbildningsprogrammet för datateknik vid Chalmers.
Förening -> Kommitté find-replace miss?

2019-03-04 14:00 UTC, viktorhallen commented on stadgar/stadgar.tex
> +Datateknologsektionen vid Chalmers, härmed benämnd teknologsektionen, är en ideell kommitté bestående av studerande vid utbildningsprogrammet för datateknik vid Chalmers.
Ooops
```suggestion
Datateknologsektionen vid Chalmers, härmed benämnd teknologsektionen, är en ideell förening bestående av studerande vid utbildningsprogrammet för datateknik vid Chalmers.
```

2019-08-08 19:08 UTC, glimfjord requested changes
Hittade en dålig find replace och korrigerade den

2019-09-02 14:01 UTC, glimfjord approved these changes

2019-09-02 14:01 UTC, merged