Ändingar verksamhetsåret 19/20 + bilfond
dtekcth/styrdokument pull request #15
Opened 2020-12-30 09:23 UTC by GusCommit

Lagt in i alla ändingar som gjordes under mitt verksamhetsår(19/20) i alla styrdokument. Lade även till bilfonden som egentligen skulle gjort för läääänge sedan men någon har missat. Se gärna över.

2020-12-30 09:51 UTC, Rembane commented
Jag tänker inte göra en ordentlig review, för det är inte min sak att göra, men jag tänker ändå föreslå att du lägger till ett r på relevant ställe i commit-meddelandet.

2020-12-30 13:23 UTC, falk-h commented
Ja vem är det som ska reviewa detta egentligen? Revisorer?

2020-12-30 13:40 UTC, GusCommit commented
Dunno, en vettig teknolog eller nått?

2020-12-30 13:43 UTC, falk-h commented
Du är la ganska vettig? Nä men om ingen annan kollar på det, påminn mig om ett par dagar så mergear jag det.

2020-12-30 14:03 UTC, Hugsim requested changes
Här var visst knappen för en riktig review, lös mina andra kommentarer så är jag nöjd.

2020-12-31 08:57 UTC, GusCommit commented
> 
> 
> Du har missat att D-Lat togs bort LP1-mötet 2019/2020, och ett par kommentarer längre upp i filen, annars ser det bra ut.

Skippade allt gällande DLat för att Kiren kirrade en pull-request(som fort. ligger kvar) med alla reglemetesändingar direkt efter det mötet. Tar och fixar resten av smågrejerna du nämnde. Hänger dock inte riktigt med på va du menar med "...och ett par kommentarer längre upp i filen...".

2020-12-31 10:47 UTC, Hugsim commented
Kommentarerna om mellanslaget som saknas och om liten bokstav i "Fri kost". Jag skrev dem i filen, men Github är svårt.

2021-01-03 13:46 UTC, Hugsim approved these changes
Snyggt jobbat! Jag är nöjd, om ingen klagar är det bara att mergea.

2021-01-03 17:32 UTC, merged